### PR TITLE
Fix for class methods named "static"

### LINKED ISSUE #13: Bug: doesn't support class functions named "static"
```js
test('supports class function named static', function (t) {
  t.doesNotThrow(function () {
    acorn.parse('class X { static () {} }', { sourceType: 'script' })
  })
  t.end()
})
```

### LINKED ISSUE #14: npm build fails
```
acorn-node on  static-fix [!?] is 📦 v2.0.0 via ⬢ v12.16.1 
⇡0% ➜ yarn build
yarn run v1.22.4
$ node build.js
acorn-bigint → ./lib/bigint/index.js
acorn-numeric-separator → ./lib/numeric-separator/index.js
acorn-dynamic-import → ./lib/dynamic-import/index.js
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'acorn-dynamic-import'
Require stack:
- /home/xyz/Development/acorn-node/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.resolve (internal/modules/cjs/helpers.js:83:19)
    at compile (/home/xyz/Development/acorn-node/build.js:11:40)
    at Object.<anonymous> (/home/xyz/Development/acorn-node/build.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/xyz/Development/acorn-node/build.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

### PR DESCRIPTION
**Pull request by kumavis**
status: ready :tada: 

Fixes #13 
Fixes #14 

@goto-bus-stop @ljharb

### CODE REVIEW

**Comment by kumavis** [comment]
build script is still broken (see #14 )
I patched the build script locally, generated the updated files, and then only included the relevant update for the sake of a minimal change. Other updates are ready in-range.

However, this patch seems to have introduced a regression with class private fields? not sure why

**Comment by kumavis** [comment]
can reproduce the regression by switching between the two parser extensions here
the build script is breaking something somehow
```js
const acorn = require("acorn")
const Parser = acorn.Parser.extend(require("acorn-static-class-features"))
// const Parser = acorn.Parser.extend(require("./lib/static-class-features"))

let target = Parser.prototype
while (target) {
  console.log(target.constructor.name)
  target = Reflect.getPrototypeOf(target)
}

const result = Parser.parse("class X { static #x = y }", { ecmaVersion: 10 })
```

**Comment by kumavis** [comment]
narrowed it down to `acorn-private-class-elements`'s transpile, though don't understand the issue yet :thinking:

**Comment by kumavis** [comment]
oof ok, solved it
unsurprisingly, the quick-and-dirty transform in the build script is brittle

**Comment by kumavis** [comment]
here is an issue for buble relating to use needing to do the replace at all https://github.com/bublejs/buble/issues/259

**Comment by kumavis** [comment]
btw there's in range updates for the following, and the dynamic import thing should be figured out 
```
	modified:   lib/class-fields/index.js
	modified:   lib/import-meta/index.js
	modified:   lib/numeric-separator/index.js
```

**Comment by goto-bus-stop** [comment]
We should def switch to Babel, I liked Bublé's smallness but AFAIK it's not actively maintained now and we're already having to pile up hacks to make the build work :sweat_smile:

**Comment by kumavis** [comment]
@goto-bus-stop thanks/ would really appreciate a patch version today if possible 🙏

**Comment by kumavis** [comment]
@goto-bus-stop sorry to bother, i would really appreciate if you could publish a patch :sparkles:

**Pull request merged**
